# Generated by Django 3.2.9 on 2022-05-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconstants',
            name='description',
            field=models.TextField(blank=True, default='Armlogi description.', null=True),
        ),
        migrations.AlterField(
            model_name='siteconstants',
            name='site_url',
            field=models.URLField(blank=True, default='https://armtk.com', null=True),
        ),
    ]
